apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-prod

bases:
  - ../../base

namePrefix: prod-

replicas:
  - name: nginx
    count: 3

commonLabels:
  environment: prod

resources:
  - hpa.yaml
  - vpa.yaml

