apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-dev

bases:
  - ../../base

namePrefix: dev-

replicas:
  - name: nginx
    count: 1

commonLabels:
  environment: dev
