apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatekeeper-system

commonLabels:
  app: gatekeeper-policy-manager
  managed-by: argocd

# Reference upstream gatekeeper-policy-manager manifests
resources:
  - https://github.com/gatekeeper-policy-manager/gatekeeper-policy-manager/deploy/kustomize?ref=main

