apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: nginx
  managed-by: argocd

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf

images:
  - name: nginx
    newTag: 1.25-alpine
