apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubecost

commonLabels:
  app: kubecost
  managed-by: argocd

helmCharts:
  - name: cost-analyzer
    repo: https://kubecost.github.io/cost-analyzer
    version: 2.8.0
    releaseName: kubecost
    valuesInline:
      global:
        prometheus:
          enabled: true
      service:
        type: LoadBalancer
        port: 9090
      ingress:
        enabled: false
      kubecostProductConfigs:
        currencyCode: USD

