
# applications/kubecost/values/kubecost-values.yaml
global:
  clusterId: in-cluster
  prometheus:
    enabled: true

kubecostProductConfigs:
  currencyCode: USD

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
  hosts:
    - kubecost.test.local
  tls: []
